name: setup
author: Adam Thornton <athornton@lsst.org>
description: set up env vars for sciplat-lab build
inputs:
  tag:
    description: 'EUPS tag of input DM Pipelines Stack container'
    required: true
    default: ''
  supplementary:
    description: 'Supplementary tag for experimental builds; yields output tag exp_tag_supplementary'
    required: false
    default: ''
  image:
    description: 'URI for output Docker image'
    required: false
    default: 'docker.io/lsstsqre/sciplat-lab'
    # someday: 'ghcr.io/lsst-sqre/sciplat-lab'
  push:
    description: 'push resulting image; make empty or set to a YAML-false string to build but not push'
    required: false
    default: 'true'
