[ NFSMount_Global_Options ]
    rw=True
    relatime=True
    vers=4.1
    rsize=1048576
    wsize=1048576
    namlen=255
    hard=True
    proto=tcp
    timeo=600
    retrans=2
    sec=sys
    local_lock=none
