#!/usr/bin/env bash
set -x
set -eo pipefail  # -u and conda don't play well: ADDR2LINE: unbound variable

TAG=$1

# First system; we prepend sciplat- so we can see what (if anything) changed
# between the base container and this one.

vi_dir="/usr/local/share/jupyterlab/versions-installed"
mkdir -p ${vi_dir}
cd ${vi_dir}
dpkg -l | tee "sciplat-system-dpkgs"
uv pip list | tee "sciplat-system-python"
if (which npm); then
    npm list --global --long --json | tee "sciplat-node-modules"
fi
uv pip tree | tee "sciplat-system-python-tree"

# Now JupyterLab python

source /usr/local/share/jupyterlab/venv/bin/activate
uv pip list | tee "sciplat-jupyterlab-python"
uv pip tree | tee "sciplat-jupyterlab-python-tree"
((jupyter labextension list 2>&1) | tee "sciplat-lab-extensions") || /bin/true
deactivate

# Now the stack
SHELL=bash
export SHELL
source /opt/lsst/software/stack/loadLSST.bash
conda env export | tee sciplat-conda-stack.yaml
# If conda-tree is installed, use it to generate a tree view of dependencies.
# If not, clean up output from the failed command
if ! (which conda tree --full > sciplat-conda-stack-tree); then
    rm -f sciplat-conda-stack-tree
fi

# Add the tutorials as they existed when the container was built, but only
# if this is a release, release candidate, or an experimental version
# thereof.
#
# Fortunately, ${TAG} is the eups version, so we don't have to care about
# any of the shenanigans we did to generate our image tag.  If it starts with
# "v", it is in the above category.
itype=$(echo ${TAG} | cut -c 1)
if [ ${itype} == "v" ]; then
    # It's a release-ish build
    cd /etc/nublado
    git clone --depth 1 "https://github.com/lsst/tutorial-notebooks" -b main \
        tutorial-notebooks-at-build-time  
fi
