#!/usr/bin/env bash
#
# This can be pretty minimal.  Effectively we just want to ensure that
# files once found in the old-style layout still exist, but point to their
# new equivalent.
#
# lsst_dask.yml and idds.cfg.client.template are copied in by nublado and
# put in /opt/lsst/software/jupyterlab, which seems fine.
#

set -euo pipefail

cd /opt/lsst/software
mkdir jupyterlab
cd jupyterlab

realdir="../../../../usr/local/share/jupyterlab"
for file in lsst_kernel.json lsstlaunch.bash; do
    ln -s "${realdir}/${file}"
done
ln -s "${realdir}/etc/20-logging.py"
ln -s "${realdir}/runlab" runlab.sh
