#!/usr/bin/env bash
set -x
set -euo pipefail

# Check out notebooks-at-build-time
# Do a shallow clone (important for the tutorials)
nbdir="/opt/lsst/software/notebooks-at-build-time"
mkdir -p "${nbdir}"
branch="prod"
notebooks="lsst-sqre/system-test rubin-dp0/tutorial-notebooks"
cd ${nbdir}
git clone --depth 1 -b prod "https://github.com/lsst-sqre/system-test"
git clone --depth 1 "https://github.com/lsst/tutorial-notebooks"
