#!/usr/bin/env bash
set -x

# -u makes lsstinstall fail, via mamba ADDR2LINE: unbound variable.
set -eo pipefail

TAG=$1

# Force the issue
SHELL=bash
export SHELL

stackdir=/opt/lsst/software/stack
sbt=https://raw.githubusercontent.com/lsst/shebangtron/main/shebangtron

mkdir -p $stackdir
cd $stackdir
curl -OL https://ls.st/lsstinstall
chmod u+x lsstinstall
./lsstinstall -T $TAG
source $stackdir/loadLSST.bash
for prod in $EUPS_PRODUCTS; do
    eups distrib install --no-server-tags -vvv "$prod" -t "$EUPS_TAG"
done
find ${stackdir} -exec strip --strip-unneeded --preserve-dates {} + \
     > /dev/null 2>&1 || true
find ${stackdir} -maxdepth 5 -name tests -type d -exec rm -rf {} + \
       > /dev/null 2>&1 || true
find ${stackdir} -maxdepth 6 \
       \( -path "*doc/html" -o -path "*doc/xml" \) -type d -exec rm -rf {} + \
       > /dev/null 2>&1 || true
find ${stackdir} -maxdepth 5 -name src -type d -exec rm -rf {} + \
       > /dev/null 2>&1 || true

for product in lsst_distrib lsst_sitcom; do
    eups distrib install -t $TAG $product
done
curl -sSL $sbt | python
setup lsst_distrib

mamba clean -a -f -y --no-banner # Not clear that -f is safe.
