#!/usr/bin/env bash
set -x
set -eo pipefail

# Set T&S cycle parms
. /tmp/build/cycle.env

LOADSTACK=/opt/lsst/software/stack/loadLSST.bash
SRCDIR=/opt/lsst/src
SALSTACK=/opt/lsst/sal/salbldsteps.bash
TZ="UTC"
OSPL_HOME=/opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux

. ${LOADSTACK}
mamba install -c conda-forge -y \
    librdkafka aiokafka astroquery asynctest \
    ephem kafkacat pre-commit pytest-tornasync \
    setuptools_scm pytest-black \
    astrometry \
    astroplan

python3 -c 'from astropy.utils.data import clear_download_cache; \
    clear_download_cache()'

# Conda install TSSW packages that are frozen. These are seldom changed by
# users during operations.

unset LD_PRELOAD
setup lsst_distrib
. ${OSPL_HOME}/release.com

mamba install -c lsstts -y \
    ts-dds=${osplice_v}=${osplice_py} \
    ts-ddsconfig=${ts_ddsconfig} \
    ts-salobj=${ts_salobj} \
    ts-idl=${ts_idl}=${ts_xml}_${ts_sal} \
    ts-atdome=${ts_atdome} \
    ts-atdometrajectory=${ts_atdometrajectory} \
    ts-atmcs-simulator=${ts_atmcssimulator} \
    ts-criopy=${ts_criopy} \
    ts-utils=${ts_utils}
