#!/usr/bin/env bash
set -x
# -u causes failure in activate: ADDR2LINE: unbound variable
set -eo pipefail
stackdir=/opt/lsst/software/stack

SHELL=bash
export SHELL

MAMBA_ROOT_PREFIX="/opt/lsst/software/stack/conda"
export MAMBA_ROOT_PREFIX

# Never allow the installation to upgrade rubin_env.  Generally enforcing
# the pin is only needed for releases, where the current version may have
# moved ahead.

# mamba is ... going away in September 2025.
profdir=$stackdir/conda/etc/profile.d
if [ -f $profdir/mamba.sh ]; then
    mv $profdir/mamba.sh $profdir/mamba.sh.save
fi

source $stackdir/loadLSST.bash

rubin_env_ver=$(conda list rubin-env$ --json | jq -r '.[0].version')

# Refactor of rubin-env-rsp coming later to separate user packages from
# Lab environment packages.
conda install -y "rubin-env-rsp==${rubin_env_ver}"

# uv is compatible with pip but much faster.
pip install uv

# These are the things that are not available on conda-forge.
# Note that we are not installing with `--upgrade`.  That is so that if
# lower-level layers have already installed the package, pinned to a version
# they need, we won't upgrade it.  But if it isn't already installed, we'll
# just take the latest available.  `--no-build-isolation` ensures that any
# source packages use C++ libraries from conda-forge.

# Nothing currently

# These are Telescope and Site packages we're putting in the base build
# to make life easier for users at USDF.  Other users can just ignore them
# and they don't have a downside other than making the image somewhat larger.

# These are available at conda-forge and are dependencies of the T&S packages.
conda install -y orjson pyside6 authlib

# These are the packages themselves, in the "lsstts" channel.
# But we cannot use these until the conda packages are compatible with
# current rubin-env and hence Python 3.13 (as of 17 Nov. 2025).
# conda install -y -c lsstts ts-m1m3-utils ts-xml ts-utils ts-salobj
#
# T&S does not publish packages to pypi.  So we have to install from
# their git repository directly, and `--no-build-isolation` may make this
# more difficult.
#
# We are going to determine the most recent tag for each repo, and install
# that, rather than a (possibly unreleased) tip.
#
# `git ls-remote` does that: `--refs --tags` says only list the tags, and
# `--sort="-version:refname"` says, list the tags with the highest version
# first.  Then throw away any alpha, beta, and rc tags.  Take the first thing
# that's left with `head -1`, and discard the commit hash with `awk`.  Finally
# extract the tag from the reference with `sed`.

tsrepos="ts_m1m3_utils ts_xml ts_utils ts_salobj"

pip_urls=""
for r in ${tsrepos}; do
    url="https://github.com/lsst-ts/${r}"
    tag=$(git ls-remote --sort="-version:refname" --refs --tags ${url} | \
	      grep -v alpha | grep -v beta | grep -v rc | \
	      head -1 | awk '{print $2}' | sed -e 's|refs/tags/||' )
    pip_url="git+${url}@${tag}"
    if [ -z "${pip_urls}" ]; then
	pip_urls=${pip_url}
    else
	pip_urls="${pip_urls} ${pip_url}"
    fi
done
    
uv pip install --no-build-isolation ${pip_urls}

# "--no-build-isolation" means we're also responsible for the dependencies
# not already provided by something in the conda env.  In this case,
# structlog and symbolicmode from lsst-rsp.
uv pip install --no-build-isolation \
    'lsst-rsp>=0.7.1' \
    structlog \
    'symbolicmode<3' \
    'jupyter_firefly_extensions>=0.15.0'

# Turn off console
jupyter labextension disable @jupyterlab/console-extension
jupyter labextension lock @jupyterlab/console-extension

# Clean caches
conda clean -a -y -f
uv cache clean

# Turn off console in UI python too
source /usr/local/share/jupyterlab/venv/bin/activate
jupyter labextension disable @jupyterlab/console-extension
jupyter labextension lock @jupyterlab/console-extension

# Add spellchecker to UI python
uv pip install jupyterlab-spellchecker
