#!/usr/bin/env bash
set -x
set -euo pipefail

# Install Jupyterlab and its runtime extensions under the system python
# (not the Stack python).  This will let us iterate the UI without having
# to worry about stack compatibility.

# First, install uv, because it's a whole lot faster than pip.

python3 -m venv /usr/local/share/jupyterlab/venv
source /usr/local/share/jupyterlab/venv/bin/activate

python3 -m pip install uv

# We need to install datashader and its dependencies first, because otherwise
# we get stuck in a nasty llvm version dependency hole.

python3 -m uv pip install --upgrade datashader

# Here we go.  Most of these are Jupyter-related.  Some (like black and mypy)
# are just a good idea.

python3 -m uv pip install --upgrade \
   astrowidgets \
   black \
   black-nb \
   bokeh \
   bqplot \
   firefly-client \
   geoviews \
   holoviews \
   ipydatawidgets \
   ipympl \
   ipyvolume \
   ipyvuetify \
   ipywebrtc \
   ipywidgets \
   jupyter \
   jupyter_bokeh \
   jupyter_firefly_extensions \
   jupyter-dash \
   jupyter-resource-usage \
   jupyter-server-proxy \
   jupyterhub \
   jupyterlab \
   jupyterlab_execute_time \
   jupyterlab_iframe \
   jupyterlab_widgets \
   lckr-jupyterlab-variableinspector \
   llvmlite \
   lsst-rsp \
   mypy \
   'nbconvert[webpdf]' \
   nbdime \
   nbval \
   panel \
   playwright \
   plotly \
   pythreejs \
   pre-commit \
   rsp-jupyter-extensions \
   ruff \
   sidecar

# Having done that, install chromium (for webpdf export)
playwright install chromium

# File sharing doesn't work in the RSP environment; remove the extension.
jupyter labextension disable "@jupyterlab/filebrowser-extension:share-file"
# And Jupyter News is just obnoxious
jupyter labextension disable "@jupyterlab/apputils-extension:announcements"
# Our RSP menu supersedes the Hub menu items
jupyter labextension disable "@jupyterlab/hub-extension:menu"

jupyter labextension lock "@jupyterlab/hub-extension:menu" \
	"@jupyterlab/apputils-extension:announcements" \
	"@jupyterlab/filebrowser-extension:share-file"

# Clean up cache
uv cache clean
