name: Manually triggered multiplatform build of sciplat-lab container

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'EUPS tag of input DM Pipelines Stack container'
        required: true
      supplementary:
        description: 'Supplementary tag for experimental builds; yields output tag exp_tag_supplementary'
        required: false
        default: ''
      image:
        description: 'fully-qualified URI for output Docker image'
        required: false
        default: 'us-central1-docker.pkg.dev/rubin-shared-services-71ec/sciplat/sciplat-lab,ghcr.io/lsst-sqre/sciplat-lab,docker.io/lsstsqre/sciplat-lab'
      push:
        description: 'push resulting image; make empty or set to a YAML-false string to build but not push'
        required: false
        default: 'true'
      input:
        description: 'input image; you probably should change at most the tag'
        required: false
        default: 'ghcr.io/lsst-sqre/nublado-jupyterlab-base:latest'

# We need actions/write if we want to do a GH App, and we need
# packages/write to push to ghcr.io with GITHUB_TOKEN
permissions:
  actions: write
  contents: read
  packages: write
  statuses: read

jobs:
  determine_tags:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      version: ${{ steps.calculate_tags.outputs.version }}
      rest_tags: ${{ steps.calculate_tags.outputs.rest_tags }}
      all_tags: ${{ steps.calculate_tags.outputs.all_tags }}
    env:
      tag: ${{ github.event.inputs.tag }}
      supplementary: ${{ github.event.inputs.supplementary }}
      image: ${{ github.event.inputs.image }}
      input: ${{ github.event.inputs.input }}

    steps:
      - name: checkout_setup
        uses: actions/checkout@v4

      - name: calculate_tags
        id: calculate_tags
        shell: bash
        run: |
          . scripts/helper-functions.sh
          all_tags=$( calculate_tags )
          version=$( echo ${all_tags} | cut -d ',' -f 1 )
          rest_tags=$( echo ${all_tags} | cut -d ',' -f 2- )
          if [ "${rest_tags}" = "${all_tags}" ]; then
              rest_tags=""
          fi
          echo "all_tags=${all_tags}" >> ${GITHUB_OUTPUT}
          echo "version=${version}" >> ${GITHUB_OUTPUT}
          echo "rest_tags=${rest_tags}" >> ${GITHUB_OUTPUT}

  build:
    needs: determine_tags
    uses: lsst-sqre/multiplatform-build-and-push/.github/workflows/build.yaml@v1
    with:
      images: ${{ github.event.inputs.image }}
      additional-tags: ${{ needs.determine_tags.outputs.rest_tags }}
      tag: ${{ needs.determine_tags.outputs.version }}
      # use-nonstandard-ghcr-token: true
      build-args: |
        input=${{ github.event.inputs.input }}
        tag=${{ github.event.inputs.tag }}
        image=${{ github.event.inputs.image }}
        supplementary=${{ github.event.inputs.supplementary }}
        version=${{ needs.determine_tags.outputs.version }}
      cache: false
      push: ${{ fromJSON(github.event.inputs.push) }}
    secrets: inherit
